# Generated by Django 4.1.1 on 2022-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_remove_application_additional_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonVoyageApplicationForLiveSeries',
        ),
        migrations.DeleteModel(
            name='PowershotApplicationForLiveSeries',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='application',
            name='How_did_you_get_to_know_about_us',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Linkedin_URL',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Name_Of_your_institution',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Which_track_did_you_want_to_pursue',
            field=models.CharField(choices=[('Web development', 'Web development'), ('Data Science', 'Data Science'), ('Computer Vision', 'Computer Vision'), ('Campus Ambassador', 'Campus Ambassador'), ('Blockchain', 'Blockchain'), ('Product Management', 'Product Management'), ('Product Management/Entrepreneur in Residence', 'Product Management/Entrepreneur in Residence'), ('App Development', 'App Development')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Your_qualifications',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
